<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="OgrenciSkorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Persist Security Info=True;User ID=sa" SettingsObjectName="OgrenciYonetimSistemi.Properties.Settings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbYariYil" Member="tbYariYils">
    <Type Name="tbYariYil">
      <Column Name="YariYilID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbYariYil_tbOgrenciPuan" Member="tbOgrenciPuans" ThisKey="YariYilID" OtherKey="YariYilID" Type="tbOgrenciPuan" />
    </Type>
  </Table>
  <Table Name="dbo.tbSubject" Member="tbSubjects">
    <Type Name="tbSubject">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Adi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Kredi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbSubject_tbOgrenciPuan" Member="tbOgrenciPuans" ThisKey="SubjectID" OtherKey="SubjectID" Type="tbOgrenciPuan" />
    </Type>
  </Table>
  <Table Name="dbo.tbSinif" Member="tbSinifs">
    <Type Name="tbSinif">
      <Column Name="SinifID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="İsim" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tbSinif_tbOgrenciler" Member="tbOgrencilers" ThisKey="SinifID" OtherKey="SinifID" Type="tbOgrenciler" />
    </Type>
  </Table>
  <Table Name="dbo.tbOgrenciPuan" Member="tbOgrenciPuans">
    <Type Name="tbOgrenciPuan">
      <Column Name="OgrenciID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YariYilID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Puan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Yil" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="tbSubject_tbOgrenciPuan" Member="tbSubject" ThisKey="SubjectID" OtherKey="SubjectID" Type="tbSubject" IsForeignKey="true" />
      <Association Name="tbYariYil_tbOgrenciPuan" Member="tbYariYil" ThisKey="YariYilID" OtherKey="YariYilID" Type="tbYariYil" IsForeignKey="true" />
      <Association Name="tbOgrenciler_tbOgrenciPuan" Member="tbOgrenciler" ThisKey="OgrenciID" OtherKey="OgrenciID" Type="tbOgrenciler" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbOgrenciler" Member="tbOgrencilers">
    <Type Name="tbOgrenciler">
      <Column Name="OgrenciID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Resim" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Adi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dob" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Pob" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cinsiyet" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="Race" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SinifID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbOgrenciler_tbOgrenciPuan" Member="tbOgrenciPuans" ThisKey="OgrenciID" OtherKey="OgrenciID" Type="tbOgrenciPuan" />
      <Association Name="tbSinif_tbOgrenciler" Member="tbSinif" ThisKey="SinifID" OtherKey="SinifID" Type="tbSinif" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.spDeleteOgrenci" Method="spDeleteOgrenci">
    <Parameter Name="ogrID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDeleteSinif" Method="spDeleteSinif">
    <Parameter Name="sinifID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDeleteSubject" Method="spDeleteSubject">
    <Parameter Name="subjectID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDeleteYariYil" Method="spDeleteYariYil">
    <Parameter Name="YariYilID" Parameter="yariYilID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spDerslerSelectAll" Method="spDerslerSelectAll">
    <ElementType Name="spDerslerSelectAllResult">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Adi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Kredi" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDonemSelectAll" Method="spDonemSelectAll">
    <ElementType Name="spDonemSelectAllResult">
      <Column Name="YariYilID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGosterOgrPuan" Method="spGosterOgrPuan">
    <Parameter Name="classID" Type="System.Int32" DbType="Int" />
    <Parameter Name="subjectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="yariYilID" Type="System.Int32" DbType="Int" />
    <ElementType Name="spGosterOgrPuanResult">
      <Column Name="OgrenciID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Adi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Puan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YariYilID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Yil" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spInsertOgrenci" Method="spInsertOgrenci">
    <Parameter Name="sinifID" Type="System.Int32" DbType="Int" />
    <Parameter Name="resim" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="isim" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dob" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pob" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="cinsiyet" Type="System.String" DbType="NVarChar(8)" />
    <Parameter Name="race" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertOgrPuan" Method="spInsertOgrPuan">
    <Parameter Name="ogrID" Type="System.Int32" DbType="Int" />
    <Parameter Name="subjectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="yariyilID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Yil" Parameter="yil" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertSinif" Method="spInsertSinif">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertSubject" Method="spInsertSubject">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="kredi" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertYariYil" Method="spInsertYariYil">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spOgrPuanSelectAll" Method="spOgrPuanSelectAll">
    <ElementType Name="spOgrPuanSelectAllResult">
      <Column Name="OgrenciID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YariYilID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Puan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Yil" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spOgrenciSecimSinifID" Method="spOgrenciSecimSinifID">
    <Parameter Name="sinifID" Type="System.Int32" DbType="Int" />
    <ElementType Name="spOgrenciSecimSinifIDResult">
      <Column Name="OgrenciID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Resim" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Adi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dob" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Pob" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cinsiyet" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="Race" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SinifID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSearchOgrenci" Method="spSearchOgrenci">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spSearchOgrenciResult">
      <Column Name="OgrenciID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Resim" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Adi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dob" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Pob" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cinsiyet" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="Race" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SinifID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSearchOgrPuan" Method="spSearchOgrPuan">
    <Parameter Name="ogrID" Type="System.Int32" DbType="Int" />
    <Parameter Name="subjectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="yariyilID" Type="System.Int32" DbType="Int" />
    <ElementType Name="spSearchOgrPuanResult">
      <Column Name="OgrenciID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YariYilID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Puan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Yil" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSinifSelectAll" Method="spSinifSelectAll">
    <ElementType Name="spSinifSelectAllResult">
      <Column Name="SinifID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="İsim" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spUpdateOgrenci" Method="spUpdateOgrenci">
    <Parameter Name="ogrenciID" Type="System.Int32" DbType="Int" />
    <Parameter Name="resim" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="isim" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dob" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pob" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="cinsiyet" Type="System.String" DbType="NVarChar(8)" />
    <Parameter Name="race" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdateOgrPuan" Method="spUpdateOgrPuan">
    <Parameter Name="ogrID" Type="System.Int32" DbType="Int" />
    <Parameter Name="subjectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="yariYilID" Type="System.Int32" DbType="Int" />
    <Parameter Name="puan" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdateSinif" Method="spUpdateSinif">
    <Parameter Name="sinifID" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdateSubject" Method="spUpdateSubject">
    <Parameter Name="subjectID" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="kredi" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spUpdateYariYil" Method="spUpdateYariYil">
    <Parameter Name="YariYilID" Parameter="yariYilID" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>