#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciYonetimSistemi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class OgrenciSkorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbYariYil(tbYariYil instance);
    partial void UpdatetbYariYil(tbYariYil instance);
    partial void DeletetbYariYil(tbYariYil instance);
    partial void InserttbSubject(tbSubject instance);
    partial void UpdatetbSubject(tbSubject instance);
    partial void DeletetbSubject(tbSubject instance);
    partial void InserttbSinif(tbSinif instance);
    partial void UpdatetbSinif(tbSinif instance);
    partial void DeletetbSinif(tbSinif instance);
    partial void InserttbOgrenciPuan(tbOgrenciPuan instance);
    partial void UpdatetbOgrenciPuan(tbOgrenciPuan instance);
    partial void DeletetbOgrenciPuan(tbOgrenciPuan instance);
    partial void InserttbOgrenciler(tbOgrenciler instance);
    partial void UpdatetbOgrenciler(tbOgrenciler instance);
    partial void DeletetbOgrenciler(tbOgrenciler instance);
    #endregion
		
		public OgrenciSkorDataContext() : 
				base(global::OgrenciYonetimSistemi.Properties.Settings.Default.DataSourceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OgrenciSkorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OgrenciSkorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OgrenciSkorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OgrenciSkorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbYariYil> tbYariYils
		{
			get
			{
				return this.GetTable<tbYariYil>();
			}
		}
		
		public System.Data.Linq.Table<tbSubject> tbSubjects
		{
			get
			{
				return this.GetTable<tbSubject>();
			}
		}
		
		public System.Data.Linq.Table<tbSinif> tbSinifs
		{
			get
			{
				return this.GetTable<tbSinif>();
			}
		}
		
		public System.Data.Linq.Table<tbOgrenciPuan> tbOgrenciPuans
		{
			get
			{
				return this.GetTable<tbOgrenciPuan>();
			}
		}
		
		public System.Data.Linq.Table<tbOgrenciler> tbOgrencilers
		{
			get
			{
				return this.GetTable<tbOgrenciler>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDeleteOgrenci")]
		public int spDeleteOgrenci([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ogrID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ogrID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDeleteSinif")]
		public int spDeleteSinif([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sinifID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sinifID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDeleteSubject")]
		public int spDeleteSubject([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> subjectID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subjectID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDeleteYariYil")]
		public int spDeleteYariYil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YariYilID", DbType="Int")] System.Nullable<int> yariYilID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yariYilID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDerslerSelectAll")]
		public ISingleResult<spDerslerSelectAllResult> spDerslerSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spDerslerSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDonemSelectAll")]
		public ISingleResult<spDonemSelectAllResult> spDonemSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spDonemSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGosterOgrPuan")]
		public ISingleResult<spGosterOgrPuanResult> spGosterOgrPuan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> classID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> subjectID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> yariYilID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), classID, subjectID, yariYilID);
			return ((ISingleResult<spGosterOgrPuanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertOgrenci")]
		public int spInsertOgrenci([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sinifID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string resim, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string isim, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(8)")] string cinsiyet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string race)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sinifID, resim, isim, dob, pob, cinsiyet, race);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertOgrPuan")]
		public int spInsertOgrPuan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ogrID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> subjectID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> yariyilID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Yil", DbType="NVarChar(30)")] string yil)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ogrID, subjectID, yariyilID, yil);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertSinif")]
		public int spInsertSinif([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertSubject")]
		public int spInsertSubject([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kredi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, kredi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spInsertYariYil")]
		public int spInsertYariYil([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spOgrPuanSelectAll")]
		public ISingleResult<spOgrPuanSelectAllResult> spOgrPuanSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spOgrPuanSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spOgrenciSecimSinifID")]
		public ISingleResult<spOgrenciSecimSinifIDResult> spOgrenciSecimSinifID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sinifID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sinifID);
			return ((ISingleResult<spOgrenciSecimSinifIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSearchOgrenci")]
		public ISingleResult<spSearchOgrenciResult> spSearchOgrenci([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<spSearchOgrenciResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSearchOgrPuan")]
		public ISingleResult<spSearchOgrPuanResult> spSearchOgrPuan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ogrID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> subjectID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> yariyilID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ogrID, subjectID, yariyilID);
			return ((ISingleResult<spSearchOgrPuanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSinifSelectAll")]
		public ISingleResult<spSinifSelectAllResult> spSinifSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spSinifSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateOgrenci")]
		public int spUpdateOgrenci([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ogrenciID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string resim, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string isim, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(8)")] string cinsiyet, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string race)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ogrenciID, resim, isim, dob, pob, cinsiyet, race);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateOgrPuan")]
		public int spUpdateOgrPuan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ogrID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> subjectID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> yariYilID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> puan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ogrID, subjectID, yariYilID, puan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateSinif")]
		public int spUpdateSinif([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sinifID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sinifID, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateSubject")]
		public int spUpdateSubject([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> subjectID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kredi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subjectID, name, kredi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spUpdateYariYil")]
		public int spUpdateYariYil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="YariYilID", DbType="Int")] System.Nullable<int> yariYilID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yariYilID, name);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbYariYil")]
	public partial class tbYariYil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YariYilID;
		
		private string _Name;
		
		private EntitySet<tbOgrenciPuan> _tbOgrenciPuans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYariYilIDChanging(int value);
    partial void OnYariYilIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public tbYariYil()
		{
			this._tbOgrenciPuans = new EntitySet<tbOgrenciPuan>(new Action<tbOgrenciPuan>(this.attach_tbOgrenciPuans), new Action<tbOgrenciPuan>(this.detach_tbOgrenciPuans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YariYilID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YariYilID
		{
			get
			{
				return this._YariYilID;
			}
			set
			{
				if ((this._YariYilID != value))
				{
					this.OnYariYilIDChanging(value);
					this.SendPropertyChanging();
					this._YariYilID = value;
					this.SendPropertyChanged("YariYilID");
					this.OnYariYilIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbYariYil_tbOgrenciPuan", Storage="_tbOgrenciPuans", ThisKey="YariYilID", OtherKey="YariYilID")]
		public EntitySet<tbOgrenciPuan> tbOgrenciPuans
		{
			get
			{
				return this._tbOgrenciPuans;
			}
			set
			{
				this._tbOgrenciPuans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbOgrenciPuans(tbOgrenciPuan entity)
		{
			this.SendPropertyChanging();
			entity.tbYariYil = this;
		}
		
		private void detach_tbOgrenciPuans(tbOgrenciPuan entity)
		{
			this.SendPropertyChanging();
			entity.tbYariYil = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSubject")]
	public partial class tbSubject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubjectID;
		
		private string _Adi;
		
		private System.Nullable<int> _Kredi;
		
		private EntitySet<tbOgrenciPuan> _tbOgrenciPuans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubjectIDChanging(int value);
    partial void OnSubjectIDChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnKrediChanging(System.Nullable<int> value);
    partial void OnKrediChanged();
    #endregion
		
		public tbSubject()
		{
			this._tbOgrenciPuans = new EntitySet<tbOgrenciPuan>(new Action<tbOgrenciPuan>(this.attach_tbOgrenciPuans), new Action<tbOgrenciPuan>(this.detach_tbOgrenciPuans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this.OnSubjectIDChanging(value);
					this.SendPropertyChanging();
					this._SubjectID = value;
					this.SendPropertyChanged("SubjectID");
					this.OnSubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kredi", DbType="Int")]
		public System.Nullable<int> Kredi
		{
			get
			{
				return this._Kredi;
			}
			set
			{
				if ((this._Kredi != value))
				{
					this.OnKrediChanging(value);
					this.SendPropertyChanging();
					this._Kredi = value;
					this.SendPropertyChanged("Kredi");
					this.OnKrediChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSubject_tbOgrenciPuan", Storage="_tbOgrenciPuans", ThisKey="SubjectID", OtherKey="SubjectID")]
		public EntitySet<tbOgrenciPuan> tbOgrenciPuans
		{
			get
			{
				return this._tbOgrenciPuans;
			}
			set
			{
				this._tbOgrenciPuans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbOgrenciPuans(tbOgrenciPuan entity)
		{
			this.SendPropertyChanging();
			entity.tbSubject = this;
		}
		
		private void detach_tbOgrenciPuans(tbOgrenciPuan entity)
		{
			this.SendPropertyChanging();
			entity.tbSubject = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSinif")]
	public partial class tbSinif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SinifID;
		
		private string _İsim;
		
		private EntitySet<tbOgrenciler> _tbOgrencilers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSinifIDChanging(int value);
    partial void OnSinifIDChanged();
    partial void OnİsimChanging(string value);
    partial void OnİsimChanged();
    #endregion
		
		public tbSinif()
		{
			this._tbOgrencilers = new EntitySet<tbOgrenciler>(new Action<tbOgrenciler>(this.attach_tbOgrencilers), new Action<tbOgrenciler>(this.detach_tbOgrencilers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinifID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SinifID
		{
			get
			{
				return this._SinifID;
			}
			set
			{
				if ((this._SinifID != value))
				{
					this.OnSinifIDChanging(value);
					this.SendPropertyChanging();
					this._SinifID = value;
					this.SendPropertyChanged("SinifID");
					this.OnSinifIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İsim", DbType="NVarChar(50)")]
		public string İsim
		{
			get
			{
				return this._İsim;
			}
			set
			{
				if ((this._İsim != value))
				{
					this.OnİsimChanging(value);
					this.SendPropertyChanging();
					this._İsim = value;
					this.SendPropertyChanged("İsim");
					this.OnİsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSinif_tbOgrenciler", Storage="_tbOgrencilers", ThisKey="SinifID", OtherKey="SinifID")]
		public EntitySet<tbOgrenciler> tbOgrencilers
		{
			get
			{
				return this._tbOgrencilers;
			}
			set
			{
				this._tbOgrencilers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbOgrencilers(tbOgrenciler entity)
		{
			this.SendPropertyChanging();
			entity.tbSinif = this;
		}
		
		private void detach_tbOgrencilers(tbOgrenciler entity)
		{
			this.SendPropertyChanging();
			entity.tbSinif = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbOgrenciPuan")]
	public partial class tbOgrenciPuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OgrenciID;
		
		private int _SubjectID;
		
		private int _YariYilID;
		
		private System.Nullable<double> _Puan;
		
		private string _Yil;
		
		private EntityRef<tbSubject> _tbSubject;
		
		private EntityRef<tbYariYil> _tbYariYil;
		
		private EntityRef<tbOgrenciler> _tbOgrenciler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOgrenciIDChanging(int value);
    partial void OnOgrenciIDChanged();
    partial void OnSubjectIDChanging(int value);
    partial void OnSubjectIDChanged();
    partial void OnYariYilIDChanging(int value);
    partial void OnYariYilIDChanged();
    partial void OnPuanChanging(System.Nullable<double> value);
    partial void OnPuanChanged();
    partial void OnYilChanging(string value);
    partial void OnYilChanged();
    #endregion
		
		public tbOgrenciPuan()
		{
			this._tbSubject = default(EntityRef<tbSubject>);
			this._tbYariYil = default(EntityRef<tbYariYil>);
			this._tbOgrenciler = default(EntityRef<tbOgrenciler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OgrenciID
		{
			get
			{
				return this._OgrenciID;
			}
			set
			{
				if ((this._OgrenciID != value))
				{
					if (this._tbOgrenciler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOgrenciIDChanging(value);
					this.SendPropertyChanging();
					this._OgrenciID = value;
					this.SendPropertyChanged("OgrenciID");
					this.OnOgrenciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					if (this._tbSubject.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubjectIDChanging(value);
					this.SendPropertyChanging();
					this._SubjectID = value;
					this.SendPropertyChanged("SubjectID");
					this.OnSubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YariYilID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int YariYilID
		{
			get
			{
				return this._YariYilID;
			}
			set
			{
				if ((this._YariYilID != value))
				{
					if (this._tbYariYil.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnYariYilIDChanging(value);
					this.SendPropertyChanging();
					this._YariYilID = value;
					this.SendPropertyChanged("YariYilID");
					this.OnYariYilIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Float")]
		public System.Nullable<double> Puan
		{
			get
			{
				return this._Puan;
			}
			set
			{
				if ((this._Puan != value))
				{
					this.OnPuanChanging(value);
					this.SendPropertyChanging();
					this._Puan = value;
					this.SendPropertyChanged("Puan");
					this.OnPuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yil", DbType="NVarChar(10)")]
		public string Yil
		{
			get
			{
				return this._Yil;
			}
			set
			{
				if ((this._Yil != value))
				{
					this.OnYilChanging(value);
					this.SendPropertyChanging();
					this._Yil = value;
					this.SendPropertyChanged("Yil");
					this.OnYilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSubject_tbOgrenciPuan", Storage="_tbSubject", ThisKey="SubjectID", OtherKey="SubjectID", IsForeignKey=true)]
		public tbSubject tbSubject
		{
			get
			{
				return this._tbSubject.Entity;
			}
			set
			{
				tbSubject previousValue = this._tbSubject.Entity;
				if (((previousValue != value) 
							|| (this._tbSubject.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbSubject.Entity = null;
						previousValue.tbOgrenciPuans.Remove(this);
					}
					this._tbSubject.Entity = value;
					if ((value != null))
					{
						value.tbOgrenciPuans.Add(this);
						this._SubjectID = value.SubjectID;
					}
					else
					{
						this._SubjectID = default(int);
					}
					this.SendPropertyChanged("tbSubject");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbYariYil_tbOgrenciPuan", Storage="_tbYariYil", ThisKey="YariYilID", OtherKey="YariYilID", IsForeignKey=true)]
		public tbYariYil tbYariYil
		{
			get
			{
				return this._tbYariYil.Entity;
			}
			set
			{
				tbYariYil previousValue = this._tbYariYil.Entity;
				if (((previousValue != value) 
							|| (this._tbYariYil.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbYariYil.Entity = null;
						previousValue.tbOgrenciPuans.Remove(this);
					}
					this._tbYariYil.Entity = value;
					if ((value != null))
					{
						value.tbOgrenciPuans.Add(this);
						this._YariYilID = value.YariYilID;
					}
					else
					{
						this._YariYilID = default(int);
					}
					this.SendPropertyChanged("tbYariYil");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbOgrenciler_tbOgrenciPuan", Storage="_tbOgrenciler", ThisKey="OgrenciID", OtherKey="OgrenciID", IsForeignKey=true)]
		public tbOgrenciler tbOgrenciler
		{
			get
			{
				return this._tbOgrenciler.Entity;
			}
			set
			{
				tbOgrenciler previousValue = this._tbOgrenciler.Entity;
				if (((previousValue != value) 
							|| (this._tbOgrenciler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbOgrenciler.Entity = null;
						previousValue.tbOgrenciPuans.Remove(this);
					}
					this._tbOgrenciler.Entity = value;
					if ((value != null))
					{
						value.tbOgrenciPuans.Add(this);
						this._OgrenciID = value.OgrenciID;
					}
					else
					{
						this._OgrenciID = default(int);
					}
					this.SendPropertyChanged("tbOgrenciler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbOgrenciler")]
	public partial class tbOgrenciler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OgrenciID;
		
		private string _Resim;
		
		private string _Adi;
		
		private System.Nullable<System.DateTime> _Dob;
		
		private string _Pob;
		
		private string _Cinsiyet;
		
		private string _Race;
		
		private System.Nullable<int> _SinifID;
		
		private EntitySet<tbOgrenciPuan> _tbOgrenciPuans;
		
		private EntityRef<tbSinif> _tbSinif;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOgrenciIDChanging(int value);
    partial void OnOgrenciIDChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnDobChanging(System.Nullable<System.DateTime> value);
    partial void OnDobChanged();
    partial void OnPobChanging(string value);
    partial void OnPobChanged();
    partial void OnCinsiyetChanging(string value);
    partial void OnCinsiyetChanged();
    partial void OnRaceChanging(string value);
    partial void OnRaceChanged();
    partial void OnSinifIDChanging(System.Nullable<int> value);
    partial void OnSinifIDChanged();
    #endregion
		
		public tbOgrenciler()
		{
			this._tbOgrenciPuans = new EntitySet<tbOgrenciPuan>(new Action<tbOgrenciPuan>(this.attach_tbOgrenciPuans), new Action<tbOgrenciPuan>(this.detach_tbOgrenciPuans));
			this._tbSinif = default(EntityRef<tbSinif>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OgrenciID
		{
			get
			{
				return this._OgrenciID;
			}
			set
			{
				if ((this._OgrenciID != value))
				{
					this.OnOgrenciIDChanging(value);
					this.SendPropertyChanging();
					this._OgrenciID = value;
					this.SendPropertyChanged("OgrenciID");
					this.OnOgrenciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(100)")]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dob", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dob
		{
			get
			{
				return this._Dob;
			}
			set
			{
				if ((this._Dob != value))
				{
					this.OnDobChanging(value);
					this.SendPropertyChanging();
					this._Dob = value;
					this.SendPropertyChanged("Dob");
					this.OnDobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pob", DbType="NVarChar(50)")]
		public string Pob
		{
			get
			{
				return this._Pob;
			}
			set
			{
				if ((this._Pob != value))
				{
					this.OnPobChanging(value);
					this.SendPropertyChanging();
					this._Pob = value;
					this.SendPropertyChanged("Pob");
					this.OnPobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="NVarChar(8)")]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Race", DbType="NVarChar(50)")]
		public string Race
		{
			get
			{
				return this._Race;
			}
			set
			{
				if ((this._Race != value))
				{
					this.OnRaceChanging(value);
					this.SendPropertyChanging();
					this._Race = value;
					this.SendPropertyChanged("Race");
					this.OnRaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinifID", DbType="Int")]
		public System.Nullable<int> SinifID
		{
			get
			{
				return this._SinifID;
			}
			set
			{
				if ((this._SinifID != value))
				{
					if (this._tbSinif.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSinifIDChanging(value);
					this.SendPropertyChanging();
					this._SinifID = value;
					this.SendPropertyChanged("SinifID");
					this.OnSinifIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbOgrenciler_tbOgrenciPuan", Storage="_tbOgrenciPuans", ThisKey="OgrenciID", OtherKey="OgrenciID")]
		public EntitySet<tbOgrenciPuan> tbOgrenciPuans
		{
			get
			{
				return this._tbOgrenciPuans;
			}
			set
			{
				this._tbOgrenciPuans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbSinif_tbOgrenciler", Storage="_tbSinif", ThisKey="SinifID", OtherKey="SinifID", IsForeignKey=true)]
		public tbSinif tbSinif
		{
			get
			{
				return this._tbSinif.Entity;
			}
			set
			{
				tbSinif previousValue = this._tbSinif.Entity;
				if (((previousValue != value) 
							|| (this._tbSinif.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbSinif.Entity = null;
						previousValue.tbOgrencilers.Remove(this);
					}
					this._tbSinif.Entity = value;
					if ((value != null))
					{
						value.tbOgrencilers.Add(this);
						this._SinifID = value.SinifID;
					}
					else
					{
						this._SinifID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbSinif");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbOgrenciPuans(tbOgrenciPuan entity)
		{
			this.SendPropertyChanging();
			entity.tbOgrenciler = this;
		}
		
		private void detach_tbOgrenciPuans(tbOgrenciPuan entity)
		{
			this.SendPropertyChanging();
			entity.tbOgrenciler = null;
		}
	}
	
	public partial class spDerslerSelectAllResult
	{
		
		private int _SubjectID;
		
		private string _Adi;
		
		private System.Nullable<int> _Kredi;
		
		public spDerslerSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this._Adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kredi", DbType="Int")]
		public System.Nullable<int> Kredi
		{
			get
			{
				return this._Kredi;
			}
			set
			{
				if ((this._Kredi != value))
				{
					this._Kredi = value;
				}
			}
		}
	}
	
	public partial class spDonemSelectAllResult
	{
		
		private int _YariYilID;
		
		private string _Name;
		
		public spDonemSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YariYilID", DbType="Int NOT NULL")]
		public int YariYilID
		{
			get
			{
				return this._YariYilID;
			}
			set
			{
				if ((this._YariYilID != value))
				{
					this._YariYilID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class spGosterOgrPuanResult
	{
		
		private int _OgrenciID;
		
		private string _Adi;
		
		private int _SubjectID;
		
		private System.Nullable<double> _Puan;
		
		private int _YariYilID;
		
		private string _Yil;
		
		public spGosterOgrPuanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciID", DbType="Int NOT NULL")]
		public int OgrenciID
		{
			get
			{
				return this._OgrenciID;
			}
			set
			{
				if ((this._OgrenciID != value))
				{
					this._OgrenciID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this._Adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Float")]
		public System.Nullable<double> Puan
		{
			get
			{
				return this._Puan;
			}
			set
			{
				if ((this._Puan != value))
				{
					this._Puan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YariYilID", DbType="Int NOT NULL")]
		public int YariYilID
		{
			get
			{
				return this._YariYilID;
			}
			set
			{
				if ((this._YariYilID != value))
				{
					this._YariYilID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yil", DbType="NVarChar(10)")]
		public string Yil
		{
			get
			{
				return this._Yil;
			}
			set
			{
				if ((this._Yil != value))
				{
					this._Yil = value;
				}
			}
		}
	}
	
	public partial class spOgrPuanSelectAllResult
	{
		
		private int _OgrenciID;
		
		private int _SubjectID;
		
		private int _YariYilID;
		
		private System.Nullable<double> _Puan;
		
		private string _Yil;
		
		public spOgrPuanSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciID", DbType="Int NOT NULL")]
		public int OgrenciID
		{
			get
			{
				return this._OgrenciID;
			}
			set
			{
				if ((this._OgrenciID != value))
				{
					this._OgrenciID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YariYilID", DbType="Int NOT NULL")]
		public int YariYilID
		{
			get
			{
				return this._YariYilID;
			}
			set
			{
				if ((this._YariYilID != value))
				{
					this._YariYilID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Float")]
		public System.Nullable<double> Puan
		{
			get
			{
				return this._Puan;
			}
			set
			{
				if ((this._Puan != value))
				{
					this._Puan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yil", DbType="NVarChar(10)")]
		public string Yil
		{
			get
			{
				return this._Yil;
			}
			set
			{
				if ((this._Yil != value))
				{
					this._Yil = value;
				}
			}
		}
	}
	
	public partial class spOgrenciSecimSinifIDResult
	{
		
		private int _OgrenciID;
		
		private string _Resim;
		
		private string _Adi;
		
		private System.Nullable<System.DateTime> _Dob;
		
		private string _Pob;
		
		private string _Cinsiyet;
		
		private string _Race;
		
		private System.Nullable<int> _SinifID;
		
		public spOgrenciSecimSinifIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciID", DbType="Int NOT NULL")]
		public int OgrenciID
		{
			get
			{
				return this._OgrenciID;
			}
			set
			{
				if ((this._OgrenciID != value))
				{
					this._OgrenciID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(100)")]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this._Resim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this._Adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dob", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dob
		{
			get
			{
				return this._Dob;
			}
			set
			{
				if ((this._Dob != value))
				{
					this._Dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pob", DbType="NVarChar(50)")]
		public string Pob
		{
			get
			{
				return this._Pob;
			}
			set
			{
				if ((this._Pob != value))
				{
					this._Pob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="NVarChar(8)")]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this._Cinsiyet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Race", DbType="NVarChar(50)")]
		public string Race
		{
			get
			{
				return this._Race;
			}
			set
			{
				if ((this._Race != value))
				{
					this._Race = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinifID", DbType="Int")]
		public System.Nullable<int> SinifID
		{
			get
			{
				return this._SinifID;
			}
			set
			{
				if ((this._SinifID != value))
				{
					this._SinifID = value;
				}
			}
		}
	}
	
	public partial class spSearchOgrenciResult
	{
		
		private int _OgrenciID;
		
		private string _Resim;
		
		private string _Adi;
		
		private System.Nullable<System.DateTime> _Dob;
		
		private string _Pob;
		
		private string _Cinsiyet;
		
		private string _Race;
		
		private System.Nullable<int> _SinifID;
		
		public spSearchOgrenciResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciID", DbType="Int NOT NULL")]
		public int OgrenciID
		{
			get
			{
				return this._OgrenciID;
			}
			set
			{
				if ((this._OgrenciID != value))
				{
					this._OgrenciID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(100)")]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this._Resim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(50)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this._Adi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dob", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dob
		{
			get
			{
				return this._Dob;
			}
			set
			{
				if ((this._Dob != value))
				{
					this._Dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pob", DbType="NVarChar(50)")]
		public string Pob
		{
			get
			{
				return this._Pob;
			}
			set
			{
				if ((this._Pob != value))
				{
					this._Pob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="NVarChar(8)")]
		public string Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this._Cinsiyet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Race", DbType="NVarChar(50)")]
		public string Race
		{
			get
			{
				return this._Race;
			}
			set
			{
				if ((this._Race != value))
				{
					this._Race = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinifID", DbType="Int")]
		public System.Nullable<int> SinifID
		{
			get
			{
				return this._SinifID;
			}
			set
			{
				if ((this._SinifID != value))
				{
					this._SinifID = value;
				}
			}
		}
	}
	
	public partial class spSearchOgrPuanResult
	{
		
		private int _OgrenciID;
		
		private int _SubjectID;
		
		private int _YariYilID;
		
		private System.Nullable<double> _Puan;
		
		private string _Yil;
		
		public spSearchOgrPuanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciID", DbType="Int NOT NULL")]
		public int OgrenciID
		{
			get
			{
				return this._OgrenciID;
			}
			set
			{
				if ((this._OgrenciID != value))
				{
					this._OgrenciID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int NOT NULL")]
		public int SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YariYilID", DbType="Int NOT NULL")]
		public int YariYilID
		{
			get
			{
				return this._YariYilID;
			}
			set
			{
				if ((this._YariYilID != value))
				{
					this._YariYilID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puan", DbType="Float")]
		public System.Nullable<double> Puan
		{
			get
			{
				return this._Puan;
			}
			set
			{
				if ((this._Puan != value))
				{
					this._Puan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yil", DbType="NVarChar(10)")]
		public string Yil
		{
			get
			{
				return this._Yil;
			}
			set
			{
				if ((this._Yil != value))
				{
					this._Yil = value;
				}
			}
		}
	}
	
	public partial class spSinifSelectAllResult
	{
		
		private int _SinifID;
		
		private string _İsim;
		
		public spSinifSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinifID", DbType="Int NOT NULL")]
		public int SinifID
		{
			get
			{
				return this._SinifID;
			}
			set
			{
				if ((this._SinifID != value))
				{
					this._SinifID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İsim", DbType="NVarChar(50)")]
		public string İsim
		{
			get
			{
				return this._İsim;
			}
			set
			{
				if ((this._İsim != value))
				{
					this._İsim = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
